config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'quotes#index'
  resources :quotes
  get 'about', to: 'quotes#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
    validates :saying, presence: true, length: { maximum: 140, minimum: 3 }
    validates :author, presence: true, length: { maximum: 50, minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order("RANDOM()").first
  end

  def create
    @quote = Quote.create(quote_params)
    if @quote.invalid?
      flash[:error] = '<strong>Could not save</strong> the data you endtered is invalid.'
    end
    redirect_to root_path
  end

  def about
  end

  private

  def quote_params
    params.require(:quote).permit(:saying, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splurty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header class="row">
      <div class="col-3">
        <%= link_to root_path, class: 'logo' do %>
        <div class="circle">
          <br />
          Skiing Is
          <br />
          The Easy 
          <br />
          Part
        </div>
        <% end %>
      </div>
      <div class="col col-sm-4 hidden-xs-down slogan">
        Splurting out nonsense about Aspen since 2019
      </div>
      <div class="col-10 offset-1 offset-sm-0 col-sm-5 links">
      <%= link_to 'Contribute', '#', data: {toggle: "modal", target: '#myModal'} %>
      &nbsp;&nbsp; 
      <%= link_to 'About', about_path %>
    </div>
  </header>

  

     <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
              <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <%= simple_form_for Quote.new do |f| %>
             <div class="modal-body">
                 <%= f.input :saying, label: "What is the saying you want to add?", placeholder: "You can't find a sandwich under $15." %>
                 <br />
                 <%= f.input :author, label: "Who is the author of the quote?", placeholder: "Ham Wallace." %>   
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <%= f.submit 'Create', class: 'btn btn-danger' %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>

   <hr />
   <br class="clear" />

   <div class="container">
      <% if flash[:error].present? %>
        <div class="col-10 offset-1 alert alert-danger">
          <%= flash[:error].html_safe %>
        </div>
        <% end %>

    <%= yield %>
   </div>
   
   <div class="footer">
    <div class="container">
      <div class="row">
        <div class="col-12 col-sm-6">
          <%= link_to "This isn't enough, I want more", root_path, class: 'next-quote' %>
        </div>
        <div class="col-12 col-sm-6 footer-blurb">
          Proudly hacked by <a href="[https://hammywallace.netlify.com/]">Ham Wallace</a><br />
          Want to build your own Splurty Web App - <a href="https://online.bootcampspot.com"> Learn how to code here</a>
        </div>
      </div>
    </div>
  </div>

  </body>
</html>

app/views/quotes/about.html.erb
<div class="col-10 offset-1 about">
  <h1>About Splurty</h1>

  <p>
    Splurty was built by <a target="_blank" href="https://hammywallace.netlify.com">Ham Wallace</a>.  A web developer who is on a mission to help the people of the world know the absurdities that exist in the town of Aspen, CO.
  </p>
  <br />
  <p>
    He alone has brought light to the issues that many didn't think existed in this funny little town.  He has warned many thousands of people of what is considered the norm.
  </p>
  <br />
  <p>
    If you want to learn more about the town visit the <a target="_blank" href="https://www.aspensnowmass.com"> website</a>.
  </p>

<div class="row">
  <div class="col-12 col-sm-4">
    <%= image_tag 'me.jpg', class: 'img-fluid' %>
  </div>

  <div class="col-12 col-sm-7 offset-sm-1">
    <h2 class="text-center">Ham Wallace</h2>
    <br />
    <p>
      Ham Wallace is a server at Meat & Cheese in Aspen, CO.  He is just getting into coding this summer and plans to gradute from the DU Coding Bootcamp with a strong ability to code for web development.
    </p>
  </div>
</div>
<br class="clear" />

</div>

<br class="clear" />
<br />
<br />
<br />
<br />

app/views/quotes/index.html.erb
<h2>
  <span>SPLURTY / No. <%= @quote.id %></span> 
  Here's the <u>best unsolicited small town advice</u> you can get!
</h2>

<h1><%= @quote.saying %></h1>
<h2 class="float-right">- <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />